//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\FEJ2AV\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://rb-tt-mscrm-d.de.bosch.com/TTCRM" /namespace:"SharedLibraries_Plugins.EntityModel" /SuppressGeneratedCodeAttribute /out:"C:\Users\FEJ2AV\Source\Repos\TTMSCRM\TTMSCRM.Plugins\SharedLibraries_Plugins\EntityModel\CrmContext.cs" /servicecontextname:"CrmContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]
[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]

namespace SharedLibraries_Plugins.EntityModel
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class CrmContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Account> AccountSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.ActivityParty"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.ActivityParty> ActivityPartySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.ActivityParty>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.alegri_autonumbercounter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.alegri_autonumbercounter> alegri_autonumbercounterSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.alegri_autonumbercounter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Appointment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Appointment> AppointmentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Appointment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Btt_gratuity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Btt_gratuity> Btt_gratuitySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Btt_gratuity>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Contact> ContactSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Email"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Email> EmailSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Email>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Opportunity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Opportunity> OpportunitySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Opportunity>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Orb_classificationbase"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Orb_classificationbase> Orb_classificationbaseSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Orb_classificationbase>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Orb_country"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Orb_country> Orb_countrySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Orb_country>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Orb_machine"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Orb_machine> Orb_machineSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Orb_machine>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Orb_productgroup"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Orb_productgroup> Orb_productgroupSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Orb_productgroup>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Orb_productgroupclassification"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Orb_productgroupclassification> Orb_productgroupclassificationSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Orb_productgroupclassification>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Orb_visitplanningbase"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Orb_visitplanningbase> Orb_visitplanningbaseSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Orb_visitplanningbase>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Product"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Product> ProductSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Product>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Quote"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Quote> QuoteSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Quote>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_apimonitor"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_apimonitor> rbtt_apimonitorSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_apimonitor>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_appliance"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_appliance> rbtt_applianceSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_appliance>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_applicationid"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_applicationid> rbtt_applicationidSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_applicationid>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_bookoffeedback"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_bookoffeedback> rbtt_bookoffeedbackSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_bookoffeedback>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_configurations"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_configurations> rbtt_configurationsSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_configurations>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_consent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_consent> rbtt_consentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_consent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_consenttext"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_consenttext> rbtt_consenttextSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_consenttext>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange> rbtt_customermasterdataexchangeSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_delivernote"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_delivernote> rbtt_delivernoteSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_delivernote>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_delivernoteitem"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_delivernoteitem> rbtt_delivernoteitemSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_delivernoteitem>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_processingactivity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_processingactivity> rbtt_processingactivitySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_processingactivity>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.rbtt_productionplants"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.rbtt_productionplants> rbtt_productionplantsSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.rbtt_productionplants>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.SdkMessage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.SdkMessage> SdkMessageSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.SdkMessage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.SdkMessageProcessingStep"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.SdkMessageProcessingStep> SdkMessageProcessingStepSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.SdkMessageProcessingStep>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.SystemUser> SystemUserSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.SystemUserRoles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.SystemUserRoles> SystemUserRolesSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.SystemUserRoles>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.Task"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.Task> TaskSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.Task>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.UoM"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.UoM> UoMSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.UoM>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SharedLibraries_Plugins.EntityModel.UoMSchedule"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SharedLibraries_Plugins.EntityModel.UoMSchedule> UoMScheduleSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SharedLibraries_Plugins.EntityModel.UoMSchedule>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
	
	/// <summary>
	/// Attribute to handle storing the OptionSet's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
	public sealed class OptionSetMetadataAttribute : System.Attribute
	{
		
		/// <summary>
		/// Color of the OptionSetValue.
		/// </summary>
		public string Color { get; set; }
		
		/// <summary>
		/// Description of the OptionSetValue.
		/// </summary>
		public string Description { get; set; }
		
		/// <summary>
		/// Display order index of the OptionSetValue.
		/// </summary>
		public int DisplayIndex { get; set; }
		
		/// <summary>
		/// External value of the OptionSetValue.
		/// </summary>
		public string ExternalValue { get; set; }
		
		/// <summary>
		/// Name of the OptionSetValue.
		/// </summary>
		public string Name { get; set; }
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
		/// </summary>
		/// <param name="name">Name of the value.</param>
		/// <param name="displayIndex">Display order index of the value.</param>
		/// <param name="color">Color of the value.</param>
		/// <param name="description">Description of the value.</param>
		/// <param name="externalValue">External value of the value.</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null)
		{
			this.Color = color;
			this.Description = description;
			this.ExternalValue = externalValue;
			this.DisplayIndex = displayIndex;
			this.Name = name;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of OptionSetMetadataAttribute.
	/// </summary>
	public static class OptionSetExtension
	{
		
		/// <summary>
		/// Returns the OptionSetMetadataAttribute for the given enum value
		/// </summary>
		/// <typeparam name="T">OptionSet Enum Type</typeparam>
		/// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
			where T :  struct, System.IConvertible
		{
			System.Type enumType = typeof(T);
			if (!enumType.IsEnum)
			{
				throw new System.ArgumentException("T must be an enum!");
			}
			System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
			for (int i = 0; (i < members.Length); i++
			)
			{
				System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
				if (attribute != null)
				{
					return ((OptionSetMetadataAttribute)(attribute));
				}
			}
			throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
		}
	}
}