//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SharedLibraries_Plugins.EntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Orb_countryState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Country
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("orb_country")]
	public partial class Orb_country : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string Orb_code = "orb_code";
			public const string Orb_countryId = "orb_countryid";
			public const string Id = "orb_countryid";
			public const string Orb_description = "orb_description";
			public const string Orb_name = "orb_name";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string rbtt_CMDMailbox = "rbtt_cmdmailbox";
			public const string rbtt_EmailTemplateGUID = "rbtt_emailtemplateguid";
			public const string rbtt_GDPRMailbox = "rbtt_gdprmailbox";
			public const string rbtt_ISO3166_Alpha_2 = "rbtt_iso3166_alpha_2";
			public const string rbtt_ISO3166_Alpha_3 = "rbtt_iso3166_alpha_3";
			public const string rbtt_ISO3166_numeric = "rbtt_iso3166_numeric";
			public const string rbtt_phoneprefix = "rbtt_phoneprefix";
			public const string rbtt_SARegion = "rbtt_saregion";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string lk_orb_country_createdby = "lk_orb_country_createdby";
			public const string lk_orb_country_createdonbehalfby = "lk_orb_country_createdonbehalfby";
			public const string lk_orb_country_modifiedby = "lk_orb_country_modifiedby";
			public const string lk_orb_country_modifiedonbehalfby = "lk_orb_country_modifiedonbehalfby";
			public const string rbtt_contact_orb_country_CMDMailbox = "rbtt_contact_orb_country_CMDMailbox";
			public const string rbtt_systemuser_orb_country_GDPRMailbox = "rbtt_systemuser_orb_country_GDPRMailbox";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Orb_country() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "orb_country";
		
		public const string EntitySchemaName = "Orb_country";
		
		public const string PrimaryIdAttribute = "orb_countryid";
		
		public const string PrimaryNameAttribute = "orb_name";
		
		public const string EntityLogicalCollectionName = "orb_countries";
		
		public const string EntitySetName = "orb_countries";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("orb_code")]
		public string Orb_code
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("orb_code");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Orb_code");
				this.SetAttributeValue("orb_code", value);
				this.OnPropertyChanged("Orb_code");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("orb_countryid")]
		public System.Nullable<System.Guid> Orb_countryId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("orb_countryid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Orb_countryId");
				this.SetAttributeValue("orb_countryid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("Orb_countryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("orb_countryid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.Orb_countryId = value;
			}
		}
		
		/// <summary>
		/// Description
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("orb_description")]
		public string Orb_description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("orb_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Orb_description");
				this.SetAttributeValue("orb_description", value);
				this.OnPropertyChanged("Orb_description");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("orb_name")]
		public string Orb_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("orb_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Orb_name");
				this.SetAttributeValue("orb_name", value);
				this.OnPropertyChanged("Orb_name");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Identify the mailbox where the Customer Master Data Update requests will be send.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_cmdmailbox")]
		public Microsoft.Xrm.Sdk.EntityReference rbtt_CMDMailbox
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("rbtt_cmdmailbox");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_CMDMailbox");
				this.SetAttributeValue("rbtt_cmdmailbox", value);
				this.OnPropertyChanged("rbtt_CMDMailbox");
			}
		}
		
		/// <summary>
		/// Identify the GUID of the template to be used to request the Customer Consent. The GUID do not include breakers
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_emailtemplateguid")]
		public string rbtt_EmailTemplateGUID
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rbtt_emailtemplateguid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_EmailTemplateGUID");
				this.SetAttributeValue("rbtt_emailtemplateguid", value);
				this.OnPropertyChanged("rbtt_EmailTemplateGUID");
			}
		}
		
		/// <summary>
		/// Identify the user mailbox to be used to send the request of the Customer Consent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_gdprmailbox")]
		public Microsoft.Xrm.Sdk.EntityReference rbtt_GDPRMailbox
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("rbtt_gdprmailbox");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_GDPRMailbox");
				this.SetAttributeValue("rbtt_gdprmailbox", value);
				this.OnPropertyChanged("rbtt_GDPRMailbox");
			}
		}
		
		/// <summary>
		/// ISO Code Alpha 2
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_iso3166_alpha_2")]
		public string rbtt_ISO3166_Alpha_2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rbtt_iso3166_alpha_2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_ISO3166_Alpha_2");
				this.SetAttributeValue("rbtt_iso3166_alpha_2", value);
				this.OnPropertyChanged("rbtt_ISO3166_Alpha_2");
			}
		}
		
		/// <summary>
		/// Iso Code Alpha 3
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_iso3166_alpha_3")]
		public string rbtt_ISO3166_Alpha_3
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rbtt_iso3166_alpha_3");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_ISO3166_Alpha_3");
				this.SetAttributeValue("rbtt_iso3166_alpha_3", value);
				this.OnPropertyChanged("rbtt_ISO3166_Alpha_3");
			}
		}
		
		/// <summary>
		/// ISO Code Numeric
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_iso3166_numeric")]
		public string rbtt_ISO3166_numeric
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rbtt_iso3166_numeric");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_ISO3166_numeric");
				this.SetAttributeValue("rbtt_iso3166_numeric", value);
				this.OnPropertyChanged("rbtt_ISO3166_numeric");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_phoneprefix")]
		public string rbtt_phoneprefix
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rbtt_phoneprefix");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_phoneprefix");
				this.SetAttributeValue("rbtt_phoneprefix", value);
				this.OnPropertyChanged("rbtt_phoneprefix");
			}
		}
		
		/// <summary>
		/// SA Region
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_saregion")]
		public Microsoft.Xrm.Sdk.OptionSetValue rbtt_SARegion
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("rbtt_saregion");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_SARegion");
				this.SetAttributeValue("rbtt_saregion", value);
				this.OnPropertyChanged("rbtt_SARegion");
			}
		}
		
		/// <summary>
		/// SA Region
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_saregion")]
		public virtual rbtt_SARegion? rbtt_SARegionEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rbtt_SARegion?)(EntityOptionSetEnum.GetEnum(this, "rbtt_saregion")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_SARegion");
				this.SetAttributeValue("rbtt_saregion", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("rbtt_SARegion");
			}
		}
		
		/// <summary>
		/// Status of the country
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<SharedLibraries_Plugins.EntityModel.Orb_countryState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((SharedLibraries_Plugins.EntityModel.Orb_countryState)(System.Enum.ToObject(typeof(SharedLibraries_Plugins.EntityModel.Orb_countryState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the country
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the country
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual Orb_country_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((Orb_country_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N btt_orb_country_opportunity_countryregion
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("btt_orb_country_opportunity_countryregion")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Opportunity> btt_orb_country_opportunity_countryregion
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Opportunity>("btt_orb_country_opportunity_countryregion", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("btt_orb_country_opportunity_countryregion");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Opportunity>("btt_orb_country_opportunity_countryregion", null, value);
				this.OnPropertyChanged("btt_orb_country_opportunity_countryregion");
			}
		}
		
		/// <summary>
		/// 1:N btt_orb_country_orb_classificationbase
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("btt_orb_country_orb_classificationbase")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Orb_classificationbase> btt_orb_country_orb_classificationbase
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Orb_classificationbase>("btt_orb_country_orb_classificationbase", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("btt_orb_country_orb_classificationbase");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Orb_classificationbase>("btt_orb_country_orb_classificationbase", null, value);
				this.OnPropertyChanged("btt_orb_country_orb_classificationbase");
			}
		}
		
		/// <summary>
		/// 1:N btt_orb_country_orb_productgroup
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("btt_orb_country_orb_productgroup")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Orb_productgroup> btt_orb_country_orb_productgroup
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Orb_productgroup>("btt_orb_country_orb_productgroup", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("btt_orb_country_orb_productgroup");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Orb_productgroup>("btt_orb_country_orb_productgroup", null, value);
				this.OnPropertyChanged("btt_orb_country_orb_productgroup");
			}
		}
		
		/// <summary>
		/// 1:N btt_orb_country_orb_visitplanningbase
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("btt_orb_country_orb_visitplanningbase")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Orb_visitplanningbase> btt_orb_country_orb_visitplanningbase
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Orb_visitplanningbase>("btt_orb_country_orb_visitplanningbase", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("btt_orb_country_orb_visitplanningbase");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Orb_visitplanningbase>("btt_orb_country_orb_visitplanningbase", null, value);
				this.OnPropertyChanged("btt_orb_country_orb_visitplanningbase");
			}
		}
		
		/// <summary>
		/// 1:N btt_orb_country_systemuser
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("btt_orb_country_systemuser")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.SystemUser> btt_orb_country_systemuser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.SystemUser>("btt_orb_country_systemuser", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("btt_orb_country_systemuser");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.SystemUser>("btt_orb_country_systemuser", null, value);
				this.OnPropertyChanged("btt_orb_country_systemuser");
			}
		}
		
		/// <summary>
		/// 1:N orb_orb_country_account
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("orb_orb_country_account")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Account> orb_orb_country_account
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Account>("orb_orb_country_account", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("orb_orb_country_account");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Account>("orb_orb_country_account", null, value);
				this.OnPropertyChanged("orb_orb_country_account");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_contact_CountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_contact_CountryId")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Contact> rbtt_orb_country_contact_CountryId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Contact>("rbtt_orb_country_contact_CountryId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_contact_CountryId");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Contact>("rbtt_orb_country_contact_CountryId", null, value);
				this.OnPropertyChanged("rbtt_orb_country_contact_CountryId");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_opportunity_ALid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_opportunity_ALid")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Opportunity> rbtt_orb_country_opportunity_ALid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Opportunity>("rbtt_orb_country_opportunity_ALid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_opportunity_ALid");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Opportunity>("rbtt_orb_country_opportunity_ALid", null, value);
				this.OnPropertyChanged("rbtt_orb_country_opportunity_ALid");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_opportunity_ConfigurationCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_opportunity_ConfigurationCountryId")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Opportunity> rbtt_orb_country_opportunity_ConfigurationCountryId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Opportunity>("rbtt_orb_country_opportunity_ConfigurationCountryId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_opportunity_ConfigurationCountryId");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Opportunity>("rbtt_orb_country_opportunity_ConfigurationCountryId", null, value);
				this.OnPropertyChanged("rbtt_orb_country_opportunity_ConfigurationCountryId");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_opportunity_OpportunityCountry
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_opportunity_OpportunityCountry")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Opportunity> rbtt_orb_country_opportunity_OpportunityCountry
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Opportunity>("rbtt_orb_country_opportunity_OpportunityCountry", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_opportunity_OpportunityCountry");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Opportunity>("rbtt_orb_country_opportunity_OpportunityCountry", null, value);
				this.OnPropertyChanged("rbtt_orb_country_opportunity_OpportunityCountry");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_orb_machine_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_orb_machine_Country")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.Orb_machine> rbtt_orb_country_orb_machine_Country
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.Orb_machine>("rbtt_orb_country_orb_machine_Country", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_orb_machine_Country");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.Orb_machine>("rbtt_orb_country_orb_machine_Country", null, value);
				this.OnPropertyChanged("rbtt_orb_country_orb_machine_Country");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_rbtt_bookoffeedback_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_rbtt_bookoffeedback_Country")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.rbtt_bookoffeedback> rbtt_orb_country_rbtt_bookoffeedback_Country
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_bookoffeedback>("rbtt_orb_country_rbtt_bookoffeedback_Country", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_rbtt_bookoffeedback_Country");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_bookoffeedback>("rbtt_orb_country_rbtt_bookoffeedback_Country", null, value);
				this.OnPropertyChanged("rbtt_orb_country_rbtt_bookoffeedback_Country");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_rbtt_consent_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_rbtt_consent_Country")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.rbtt_consent> rbtt_orb_country_rbtt_consent_Country
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_consent>("rbtt_orb_country_rbtt_consent_Country", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_rbtt_consent_Country");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_consent>("rbtt_orb_country_rbtt_consent_Country", null, value);
				this.OnPropertyChanged("rbtt_orb_country_rbtt_consent_Country");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_rbtt_consenttext_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_rbtt_consenttext_Country")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.rbtt_consenttext> rbtt_orb_country_rbtt_consenttext_Country
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_consenttext>("rbtt_orb_country_rbtt_consenttext_Country", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_rbtt_consenttext_Country");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_consenttext>("rbtt_orb_country_rbtt_consenttext_Country", null, value);
				this.OnPropertyChanged("rbtt_orb_country_rbtt_consenttext_Country");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_rbtt_customermasterdataexchange_Country_New
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange> rbtt_orb_country_rbtt_customermasterdataexchange_Country_New
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange>("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange>("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New", null, value);
				this.OnPropertyChanged("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_rbtt_customermasterdataexchange_Country_New_Address
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New_Address")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange> rbtt_orb_country_rbtt_customermasterdataexchange_Country_New_Address
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange>("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New_Address", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New_Address");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange>("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New_Address", null, value);
				this.OnPropertyChanged("rbtt_orb_country_rbtt_customermasterdataexchange_Country_New_Address");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange> rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange>("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange>("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old", null, value);
				this.OnPropertyChanged("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old_Address
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old_Address")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange> rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old_Address
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange>("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old_Address", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old_Address");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_customermasterdataexchange>("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old_Address", null, value);
				this.OnPropertyChanged("rbtt_orb_country_rbtt_customermasterdataexchange_Country_Old_Address");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_rbtt_processingactivity_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_rbtt_processingactivity_Country")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.rbtt_processingactivity> rbtt_orb_country_rbtt_processingactivity_Country
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_processingactivity>("rbtt_orb_country_rbtt_processingactivity_Country", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_rbtt_processingactivity_Country");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_processingactivity>("rbtt_orb_country_rbtt_processingactivity_Country", null, value);
				this.OnPropertyChanged("rbtt_orb_country_rbtt_processingactivity_Country");
			}
		}
		
		/// <summary>
		/// 1:N rbtt_orb_country_rbtt_productionplants_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_orb_country_rbtt_productionplants_Country")]
		public System.Collections.Generic.IEnumerable<SharedLibraries_Plugins.EntityModel.rbtt_productionplants> rbtt_orb_country_rbtt_productionplants_Country
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_productionplants>("rbtt_orb_country_rbtt_productionplants_Country", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_orb_country_rbtt_productionplants_Country");
				this.SetRelatedEntities<SharedLibraries_Plugins.EntityModel.rbtt_productionplants>("rbtt_orb_country_rbtt_productionplants_Country", null, value);
				this.OnPropertyChanged("rbtt_orb_country_rbtt_productionplants_Country");
			}
		}
		
		/// <summary>
		/// N:1 lk_orb_country_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_orb_country_createdby")]
		public SharedLibraries_Plugins.EntityModel.SystemUser lk_orb_country_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("lk_orb_country_createdby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_orb_country_createdby");
				this.SetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("lk_orb_country_createdby", null, value);
				this.OnPropertyChanged("lk_orb_country_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_orb_country_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_orb_country_createdonbehalfby")]
		public SharedLibraries_Plugins.EntityModel.SystemUser lk_orb_country_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("lk_orb_country_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_orb_country_createdonbehalfby");
				this.SetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("lk_orb_country_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_orb_country_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_orb_country_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_orb_country_modifiedby")]
		public SharedLibraries_Plugins.EntityModel.SystemUser lk_orb_country_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("lk_orb_country_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_orb_country_modifiedby");
				this.SetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("lk_orb_country_modifiedby", null, value);
				this.OnPropertyChanged("lk_orb_country_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_orb_country_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_orb_country_modifiedonbehalfby")]
		public SharedLibraries_Plugins.EntityModel.SystemUser lk_orb_country_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("lk_orb_country_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_orb_country_modifiedonbehalfby");
				this.SetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("lk_orb_country_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_orb_country_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 rbtt_contact_orb_country_CMDMailbox
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_cmdmailbox")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_contact_orb_country_CMDMailbox")]
		public SharedLibraries_Plugins.EntityModel.Contact rbtt_contact_orb_country_CMDMailbox
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SharedLibraries_Plugins.EntityModel.Contact>("rbtt_contact_orb_country_CMDMailbox", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_contact_orb_country_CMDMailbox");
				this.SetRelatedEntity<SharedLibraries_Plugins.EntityModel.Contact>("rbtt_contact_orb_country_CMDMailbox", null, value);
				this.OnPropertyChanged("rbtt_contact_orb_country_CMDMailbox");
			}
		}
		
		/// <summary>
		/// N:1 rbtt_systemuser_orb_country_GDPRMailbox
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rbtt_gdprmailbox")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rbtt_systemuser_orb_country_GDPRMailbox")]
		public SharedLibraries_Plugins.EntityModel.SystemUser rbtt_systemuser_orb_country_GDPRMailbox
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("rbtt_systemuser_orb_country_GDPRMailbox", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rbtt_systemuser_orb_country_GDPRMailbox");
				this.SetRelatedEntity<SharedLibraries_Plugins.EntityModel.SystemUser>("rbtt_systemuser_orb_country_GDPRMailbox", null, value);
				this.OnPropertyChanged("rbtt_systemuser_orb_country_GDPRMailbox");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Orb_country(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["orb_countryid"] = base.Id;
                        break;
                    case "orb_countryid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}